### ISSUE TITLE
error: cannot estimate gas; transaction may fail or may require manual gas limit

### ISSUE THREAD

**Issue by cartercameron1** [UniversityDAO/udao#21]
Hitting an error when calling the propose() function in the Open Zeppelin contracts.

**Comment by victor-wei126** [comment]
I figured out the bug. Basically, the receiver of the minted NFT *must* call the `delegate()` function in order to delegate themselves (or whoever) as the delegate who has control over using that minted NFT as voting power. Then and only then is the voting power actually granted to the receiver. Otherwise, all the receiver has is just a "plain" NFT that does nothing.

More detail: when `_afterTokenTransfer()` is called, this function [here](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/governance/utils/Votes.sol#L139-L151) is then called. That function calls `_moveDelegateVotes`, but it if you notice carefully it calls `delegates(from)` and `delegates(to)`, which both return the 0x0 null address since the delegates for both addresses haven't been set yet. So when entering the body of `_moveDelegateVotes`, the first conditional [if check](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/governance/utils/Votes.sol#L161) fails.
